/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exercise_hzw_com_ndkdemo_Jni */

#ifndef _Included_exercise_hzw_com_ndkdemo_Jni
#define _Included_exercise_hzw_com_ndkdemo_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exercise_hzw_com_ndkdemo_Jni
 * Method:    getKey
 * Signature: (Landroid/content/pm/Signature;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_exercise_hzw_com_ndkdemo_Jni_getKey
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
